class testing 
#This class will compare the three methods that 
#were used for generating the recomendations

#Function to test the accuracy of item-based
def item_b_accuracy (gen_rec, actual_scores) :
    '''
    This function takes in the list of recomendations that 
    were created with the item-based classifier and a list of 
    the actual scores users gave to the movies that the algorithm 
    recomended and outputs the percentage of accuracy that the 
    algorithm had 
    '''
#Function to test the accuracy of user-based
def user_b_accuracy (gen_rec, actual_scores) :
    '''
    This function behaves in the same way that the function above
    except that the gen_rec input is the list generated by the 
    user-based clasifier
    '''
#Function to test the accuracy of combined-based
def combined_b_accuracy (gen_rec, actual_scores) :
    '''
    This function behaves in the same way that the function above
    except that the gen_rec input is the list generated by the 
    combined-based clasifier
    '''
#This function takes in the values that the three functions above gave and 
#returns the name of the classifier that performed better
 def determine_best (user,item,combined) :
        